#!/bin/bash
echo "=== Gmail API Setup ==="
echo ""
echo "1. Go to: https://console.cloud.google.com/"
echo "2. Create new project (or select existing)"
echo "3. Enable Gmail API:"
echo "   - Click 'Enable APIs and Services'"
echo "   - Search 'Gmail API'"
echo "   - Click 'Enable'"
echo ""
echo "4. Create OAuth credentials:"
echo "   - Go to 'Credentials' > 'Create Credentials' > 'OAuth client ID'"
echo "   - Application type: 'Other'"
echo "   - Download the JSON file"
echo "   - Save as: credentials.json in ~/dapp/leadservice/"
echo ""
echo "5. Install Python libraries:"
pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client
echo ""
echo "Done! Run: python scripts/gmail_auto_check.py"
